// <auto-generated />
namespace MyShopLearning.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStreet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStreet));
        
        string IMigrationMetadata.Id
        {
            get { return "201911120038046_AddStreet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
